CREATE TABLE IF NOT EXISTS TrainingsToEquipments
(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id int,
    training_id int,
    CONSTRAINT TTE_TrainingId FOREIGN KEY (training_id)
        REFERENCES Training (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT TTE_EquipmentId FOREIGN KEY (equipment_id)
        REFERENCES Equipment (id) ON DELETE CASCADE ON UPDATE CASCADE
);