CREATE TABLE IF NOT EXISTS SanAnswer
(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer int,
    day_id int,
    question_id int,
    CONSTRAINT SA_DayId FOREIGN KEY (day_id)
        REFERENCES Day (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SA_QuestionId FOREIGN KEY (question_id)
        REFERENCES SanQuestion (id) ON DELETE CASCADE ON UPDATE CASCADE
);