CREATE TABLE IF NOT EXISTS TrainingExercise
(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work int default (1),
    rest int default (1),
    length int default (0),
    repeats int default (0),
    series int default (0),
    note text default (''),
    minutes int default (0),
    hrAvg int,
    training_id int,
    exercise_id int,
    style_id int,
    tempo_id int,
    zone_id int,
    borg_id int,
    CONSTRAINT TE_TrainingId FOREIGN KEY (training_id)
        REFERENCES Training (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT TE_ExerciseId FOREIGN KEY (exercise_id)
        REFERENCES Exercise (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT TE_StyleId FOREIGN KEY (style_id)
        REFERENCES Style (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT TE_TempoId FOREIGN KEY (tempo_id)
        REFERENCES Tempo (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT TE_ZoneId FOREIGN KEY (zone_id)
        REFERENCES Zone (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT TE_BorgId FOREIGN KEY (borg_id)
        REFERENCES Borg (id) ON DELETE SET NULL ON UPDATE CASCADE
);