CREATE TABLE IF NOT EXISTS SeasonPlan
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text default(''),
    userId text,
    start date default(current_date),
    male varchar(5) default('М'),
    hrMax int default (200),
    hrRest int default (60),
    lastPerformance int default (0),
    UNIQUE(name, start, userId)
);