CREATE TABLE IF NOT EXISTS Training
(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity int default (0),
    day_id int,
    time_id int,
    place_id int,
    borg_id int,
    CONSTRAINT T_DayId FOREIGN KEY (day_id)
        REFERENCES Day (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT T_TimeId FOREIGN KEY (time_id)
        REFERENCES Time (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT T_PlaceId FOREIGN KEY (place_id)
        REFERENCES TrainingPlace (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT T_BorgId FOREIGN KEY (borg_id)
        REFERENCES Borg (id) ON DELETE SET NULL ON UPDATE CASCADE
);