CREATE TABLE IF NOT EXISTS Day
(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date,
    capacity int default (0),
    health int default (0),
    mood int default (0),
    activity int default (0),
    dream int default (0),
    block_id   int,
    stage_id int,
    camp_id int,
    type_id int,
    competition_to_importance_id int,
    season_plan_id int,
    CONSTRAINT D_SeasonPlanId FOREIGN KEY (season_plan_id)
        REFERENCES SeasonPlan (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT D_CompetitionToImportanceId FOREIGN KEY (competition_to_importance_id)
        REFERENCES CompetitionToImportance (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT D_BlockId FOREIGN KEY (block_id)
        REFERENCES Block (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT D_StageId FOREIGN KEY (stage_id)
        REFERENCES Stage (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT D_CampId FOREIGN KEY (camp_id)
        REFERENCES Camp (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT D_TypeId FOREIGN KEY (type_id)
        REFERENCES Type (id) ON DELETE SET NULL ON UPDATE CASCADE
);